In [38]:
import numpy as np
import math as m
import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px
from sklearn.cluster import DBSCAN
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import silhouette_score
import warnings
warnings.filterwarnings(action='ignore') 

In [39]:
train_data = pd.read_csv("./dataset/train_data.csv")
features = ["air_end_temp", "motor_current"]
X = train_data[features]
X.head(2)

air_end_temp  motor_current
0         41.00          20.53
1         59.28          38.40

In [40]:
fig = px.scatter(X, x="air_end_temp", y="motor_current")
fig.show()

In [41]:
mins = 8
nn = NearestNeighbors(n_neighbors=mins+1, radius=0.4)
nn.fit(X[['air_end_temp', 'motor_current']])
distances, neighbors = nn.kneighbors(X[['air_end_temp', 'motor_current']])

In [42]:
distances

array([[0.        , 0.01414214, 0.02236068, ..., 0.15556349, 0.15556349,
        0.15556349],
       [0.        , 0.        , 0.03605551, ..., 0.07071068, 0.10630146,
        0.12041595],
       [0.        , 0.        , 0.01414214, ..., 0.05656854, 0.06403124,
        0.11313708],
       ...,
       [0.        , 0.        , 0.01414214, ..., 0.07071068, 0.07071068,
        0.12041595],
       [0.        , 0.01414214, 0.02828427, ..., 0.09899495, 0.12041595,
        0.12041595],
       [0.        , 0.01414214, 0.01414214, ..., 0.08485281, 0.08485281,
        0.08485281]])

In [43]:
neighbors

array([[   0, 2330, 2438, ..., 1550, 2171, 1487],
       [2003,    1,  269, ...,  104, 1672,  295],
       [   2,   50, 2331, ..., 2281, 2312,    4],
       ...,
       [2460,  174, 1785, ..., 2050, 2088,   70],
       [2461, 2223, 1746, ..., 1473,  100, 2080],
       [2462, 2198, 1882, ..., 1879, 2247,  407]], dtype=int64)

In [44]:
distances = np.sort(distances[:, mins], axis = 0)
distances

array([0.02828427, 0.03605551, 0.03605551, ..., 1.5467385 , 1.91175312,
       2.20988687])

In [45]:
distance_df = pd.DataFrame({"distances": distances, 
                           "index": list(range(0, len(distances)))})

In [46]:
distance_df

distances  index
0      0.028284      0
1      0.036056      1
2      0.036056      2
3      0.036056      3
4      0.036056      4
...         ...    ...
2458   1.352072   2458
2459   1.414214   2459
2460   1.546739   2460
2461   1.911753   2461
2462   2.209887   2462

[2463 rows x 2 columns]

In [47]:
fig = px.scatter(distance_df, x="index", y="distances")
fig.show()